name: crx artifacts to release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "."
          zipFilePath: "build/my-extension.zip"

      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: "build/my-extension.zip"
          crxFilePath: "build/my-extension.crx"
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }},

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/my-extension.crx
